# Generated by Django 3.2.4 on 2021-06-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apollo', '0007_player_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetword',
            name='path',
            field=models.CharField(default="{'word_list': ['word1']}", max_length=1000),
        ),
    ]
