# Generated by Django 3.2.4 on 2021-09-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apollo', '0010_alter_player_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='path',
            field=models.CharField(default='{"word_list": ["word1"]}', max_length=1000),
        ),
    ]
